export const TRAER_TODOS = 'geneticas_traer_todos'
export const TRAER_UNO = 'geneticas_traer_uno'
export const LOADING = 'geneticas_cargando'
export const ERROR = 'geneticas_error'
export const ERROR_FORM = 'geneticas_error_form'
export const CAMBIO_ESTADO_FORM = 'geneticas_cambio_estado_form'

export const CAMBIO_GENETICA_ID = 'geneticas_cambio_genetica_id'
export const CAMBIO_GENETICA_NAME = 'geneticas_cambio_genetica_name'
export const CAMBIO_GENETICA_MARCA_ID = 'geneticas_cambio_genetica_marca_id'
export const CAMBIO_GENETICA_THC = 'geneticas_cambio_genetica_thc'
export const CAMBIO_GENETICA_CBD = 'geneticas_cambio_genetica_cbd'
export const CAMBIO_GENETICA_PROD_INT = 'geneticas_cambio_genetica_prod_int'
export const CAMBIO_GENETICA_PROD_EXT = 'geneticas_cambio_genetica_prod_ext'
export const CAMBIO_GENETICA_TIEMPO_FLORA = 'geneticas_cambio_genetica_tiempo_flora'
export const CAMBIO_GENETICA_SABORES = 'geneticas_cambio_genetica_sabores'

export const RECARGA = 'geneticas_recarga_genetica'
export const CANCELAR = 'geneticas_cancelar_genetica'
export const GUARDAR = 'geneticas_guardar_genetica'

