export const TRAER_TODOS = 'geneticas_traer_todos'
export const TRAER_UNO = 'geneticas_traer_uno'
export const LOADING = 'geneticas_cargando'
export const ERROR = 'geneticas_error'
export const ERROR_FORM = 'geneticas_error_form'
export const CAMBIO_GENETICA_ID = 'geneticas_cambio_genetica_id'
export const CAMBIO_GENETICA_MARCA_ID = 'geneticas_cambio_genetica_marca_id'
export const CAMBIO_GENETICA_NAME = 'geneticas_cambio_genetica_name'
export const CAMBIO_ESTADO_FORM = 'geneticas_cambio_estado_form'
export const GUARDAR = 'geneticas_guardar_marca'

