export const TRAER_TODOS = 'prototypes_traer_todos'
export const TRAER_UNO = 'prototypes_traer_uno'
export const LOADING = 'prototypes_cargando'
export const CHART_LOADING = 'prototypes_chart_loading'
export const STEPPER_DETALLE_LOADING = 'prototypes_stepper_detalle_loading'
export const ERROR = 'prototypes_error'
export const ERROR_FORM = 'prototypes_error_form'
export const CAMBIO_ESTADO_FORM = 'prototypes_cambio_estado_form'
export const CAMBIAR_ESTADO_DETALLE = 'prototypes_cambio_estado_detalle'
export const CAMBIAR_STATE_CHART = 'prototypes_cambio_state_chart'
export const CAMBIAR_FORMAT_CHART = 'prototypes_cambio_format_chart'
export const TRAER_TODOS_MONITORS = 'prototypes_traer_todos_monitors'

export const CAMBIO_PROTOTYPE_ID = 'prototypes_cambio_prototype_id'
export const CAMBIO_PROTOTYPE_NAME = 'prototypes_cambio_prototype_name'
export const CAMBIO_PROTOTYPE_GENETICA_ID = 'prototypes_cambio_prototype_prototype_id'
export const CAMBIO_PROTOTYPE_AMBIENTE_ID = 'prototypes_cambio_prototype_amiente_id'
export const CAMBIO_PROTOTYPE_SENSOR_ID = 'prototypes_cambio_prototype_sensor_id'
export const CAMBIO_PROTOTYPE_FECHA_ESTADO_A = 'prototypes_cambio_prototype_fecha_estado_a'
export const CAMBIO_PROTOTYPE_FECHA_ESTADO_B = 'prototypes_cambio_prototype_fecha_estado_b'
export const CAMBIO_PROTOTYPE_FECHA_ESTADO_C = 'prototypes_cambio_prototype_fecha_estado_c'
export const CAMBIO_PROTOTYPE_FECHA_ESTADO_D = 'prototypes_cambio_prototype_fecha_estado_d'
export const CAMBIO_PROTOTYPE_FECHA_ESTADO_E = 'prototypes_cambio_prototype_fecha_estado_e'
export const CAMBIO_PROTOTYPE_CANTIDAD = 'prototypes_cambio_prototype_cantidad'

export const RECARGA = 'prototypes_recarga_prototypes'
export const CANCELAR = 'prototypes_cancelar_prototypes'
export const GUARDAR = 'prototypes_guardar_prototype'