export const TRAER_TODOS = 'users_traer_todos'
export const TRAER_UNO = 'users_traer_uno'
export const LOADING = 'users_cargando'
export const ERROR = 'users_error'
export const CAMBIO_USUARIO_NAME = 'users_cambio_user_name'
export const CAMBIO_USUARIO_EMAIL = 'users_cambio_user_email'
export const CAMBIO_USUARIO_PASSWORD = 'users_cambio_user_password'
export const GUARDAR = 'users_guardar_user'